### ISSUE TITLE
App C fails to upload Excel file

### ISSUE THREAD

**Issue by aakbarie** [carlganz/CSP2017#1]
When I download on main screen and try to upload, the file gets uploaded but it does not show changes to the file or the contents of the file

**Comment by carlganz** [comment]
Really? I have photo evidence that it works: https://github.com/carlganz/CSP2017/blob/master/inst/App_C/README.md

Are you sure you saved changes to excel file?

**Comment by aakbarie** [comment]
Ha. No. It worked now. Sorry, but it does feel good to scare you. :)

**Comment by carlganz** [comment]
![Colbert screaming](http://replygif.net/i/120.gif)
